stages:
  - build

build:
  tags:
    - windows
  stage: build
  script:
    - bin/gmad create -folder dj_eban -out djeban.gma 
    - bin/gmad create -folder clientside -out clientside.gma
    - bin/gmad create -folder billjihad -out billjihad.gma
  artifacts:
    expire_in: 10min
    untracked: true
