variables:
  PROJECT_NAME: "GARRYS MOD UPDATE+"
stages:
  - build
  - deploy

build:
  tags:
    - windows
  stage: build
  script:
    - gmad create -folder dj_eban -out djeban.gma 
    - gmad create -folder clientside -out clientside.gma
    - gmad create -folder billjihad -out billjihad.gma
  artifacts:
    expire_in: 10min
    untracked: true

deploy:
  tags:
    - windows
  stage: deploy
  script:
    - gmpublish update -id 2501954788 -addon djeban.gma -icon djeban.jpg -changes "See https://gitlab.gamerparty.eu/kgaab/strubel_garrysmod"
    - gmpublish update -id 2187239728 -addon clientside.gma -icon clientside.jpg -changes "See https://gitlab.gamerparty.eu/kgaab/strubel_garrysmod"
    - gmpublish update -id 1962795988 -addon billjihad.gma -icon billjihad.jpg -changes "See https://gitlab.gamerparty.eu/kgaab/strubel_garrysmod"
